class JobNotFoundError(Exception):
    pass


class RetryJobError(Exception):
    pass
